### ISSUE TITLE
instructions.rs Opcodes not sorted alphabetically.

### ISSUE THREAD

**Issue by jezeke** [farazsth98/firefaith#1]
Contents of enum Opcode at instruction.rs:2 are in an arbitrary order. Please consider reordering to
 ```
pub enum Opcode {
  ADD,
  DIV,
  HLT,
  IGL,
  JMP,
  JMPB,
  JMPF,
  LOAD,
  MOV,
  MUL,
  SUB,
}
```

**Comment by farazsth98** [comment]
They are ordered based on the order I added them, please dont judge

**Comment by liampwll** [comment]
Contents of your name are in an arbitrary order. Please consider reordering to `eeejkz`
